### ISSUE TITLE
error happens when main function's called

### ISSUE THREAD

**Issue by t-cool** [singy15/sikisai-sample#1]
The error occurs when I call the main function.

```
This is SBCL 1.4.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :sikisai-sample)
To load "sikisai-sample":
  Load 1 ASDF system:
    sikisai-sample
; Loading "sikisai-sample"
.......
(:SIKISAI-SAMPLE)
* (SIKISAI-SAMPLE:main)

debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {1001936C83}>:
  The function CL-GLUT:STROKE-STRING is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE      ] Retry calling CL-GLUT:STROKE-STRING.
  1: [USE-VALUE     ] Call specified function.
  2: [RETURN-VALUE  ] Return specified values.
  3: [RETURN-NOTHING] Return zero values.
  4: [ABORT         ] Exit debugger, returning to top level.

("undefined function" #.(SB-SYS:INT-SAP #X7FFF98E98AC0) "SIKISAI")
0] 
```
My environment is:
- macOS High Sierra
- sbcl 1.4.0

**Comment by singy15** [comment]
Sikisai needs FreeGLUT and CL-GLUT:STROKE-STRING is FreeGLUT feature.
Probably Sikisai under your environment uses GLUT (NOT FreeGLUT, they are not same).
That's why this error occurs in your environment.
You can use FreeGLUT or wait for my fix for this issue.

**Comment by t-cool** [comment]
Thank you for your reply.
I installed freeGLUT through brew on my macbook.
It's located at /usr/local/Cellar/freeglut.
Should I change some codes in the sample project?
I cannot start main function yet.

**Comment by singy15** [comment]
No need to modify the code.
It seems Sikisai still uses GLUT.
I changed some codes for compatibility with GLUT.
Could you try "develop" branch?

**Comment by t-cool** [comment]
Trying the develop branch, I made it!
Thank you for your advice.
